import type { Redirect } from 'next/dist/lib/load-custom-routes';

export const redirects: Redirect[] = [
  { source: '/home', destination: '/', permanent: true },
  { source: '/about-us', destination: '/about', permanent: true },
  { source: '/contact-us', destination: '/contact', permanent: true },
  { source: '/landscaping-services', destination: '/services', permanent: true },
  { source: '/lawn-services', destination: '/services', permanent: true },
  { source: '/other-services', destination: '/services', permanent: true },
  { source: '/hardscaping', destination: '/services', permanent: true },
  { source: '/landscaping', destination: '/services/landscaping', permanent: true },
  { source: '/landscape-design', destination: '/services/landscape-design', permanent: true },
  { source: '/landscape-construction', destination: '/services/landscape-construction', permanent: true },
  { source: '/commercial-landscaping', destination: '/services/commercial-landscaping', permanent: true },
  { source: '/commercial-garden-design', destination: '/services/commercial-garden-design', permanent: true },
  { source: '/lawn-care', destination: '/services/lawn-care', permanent: true },
  { source: '/lawn-mowing', destination: '/services/lawn-mowing', permanent: true },
  { source: '/commercial-lawn-mowing', destination: '/services/commercial-lawn-mowing', permanent: true },
  { source: '/aeration', destination: '/services/aeration', permanent: true },
  { source: '/fertilization', destination: '/services/fertilization', permanent: true },
  { source: '/sodding', destination: '/services/sodding', permanent: true },
  { source: '/lawn-pest-control', destination: '/services/lawn-pest-control', permanent: true },
  { source: '/hardscapes', destination: '/services/hardscapes', permanent: true },
  { source: '/retaining-walls', destination: '/services/retaining-walls', permanent: true },
  { source: '/irrigation', destination: '/services/irrigation', permanent: true },
  { source: '/sprinklers', destination: '/services/sprinklers', permanent: true },
  { source: '/mulching', destination: '/services/mulching', permanent: true },
  { source: '/shrubs-and-hedges', destination: '/services/shrubs-and-hedges', permanent: true },
  { source: '/tree-removal', destination: '/services/tree-removal', permanent: true },
  { source: '/xeriscaping', destination: '/services/xeriscaping', permanent: true },
  { source: '/commercial-property-maintenance', destination: '/services/commercial-property-maintenance', permanent: true },
  { source: '/commercial-snow-removal', destination: '/services/commercial-snow-removal', permanent: true },
];
